name: 'sign-container'
description:  'Sign a container image'
inputs:
  container-repository-name:
    description: 'The name of the container repository'
    required: true
    type: string
  container-registry-name:
    description: 'The name of the container registry'
    type: string
    default: ghcr.io/microsoft/azure-orbital-space-sdk
  container-repository-tag:
    description: 'The tag of the container repository'
    type: string
  cosign-public-key:
    description: 'The public key to sign the container image'
    required: true
    type: string
  cosign-private-key:
    description: 'The private key to sign the container image'
    required: true
    type: string
  cosign-passphrase:
    description: 'The passphrase to sign the container image'
    required: true
    type: string
runs:
    using: 'composite'
    steps:
        - name: Sign container image
          shell: bash
          env:
            COSIGN_PASSWORD: ${{ inputs.cosign-passphrase }}
            COSIGN_KEY: ${{ inputs.cosign-private-key }}
          run: |
            if [[ -n "${{ inputs.container-repository-tag }}" ]]; then
              echo "Container repository tag set, using ${{ inputs.container-repository-tag }}"
              CONTAINER_TAG="${{ inputs.container-repository-tag }}"
            else
              echo "Container repository tag not set, checking env file"
              if [ -f "/var/spacedev/env/spacefx.env" ]; then
                echo "Source File found, loading environment variables"
                source /var/spacedev/env/spacefx.env
                CONTAINER_TAG="$SPACEFX_VERSION-$SPACEFX_CHANNEL"
                echo "Container tag is $CONTAINER_TAG"
              else
                echo "No source file found, exiting..."
                exit 1
              fi
            fi
            
            echo "Creating temp key..."
            mkdir -p ./tmp
            echo "${{ inputs.cosign-private-key }}" > ./tmp/cosign.key
            chmod 600 ./tmp/cosign.key
            echo "${{ inputs.cosign-public-key }}" > ./tmp/cosign.pub
            chmod 600 ./tmp/cosign.pub

            echo "Performing signing"
            cosign sign --tlog-upload=false --key ./tmp/cosign.key --recursive ${{ inputs.container-registry-name }}/${{ inputs.container-repository-name }}:$CONTAINER_TAG
            echo "Perform Verification Test"
            cosign verify --key ./tmp/cosign.pub ${{ inputs.container-registry-name }}/${{ inputs.container-repository-name }}:$CONTAINER_TAG
            
