name: 'run-build-containerImage'
description:  'Runs the build container image script'
inputs:
    env-file:
        description: 'Path to the env file'
        default: /var/spacedev/env/spacefx.env
    docker-file:
        description: 'Path to the docker file'
        default: Dockerfiles/Dockerfile
    architecture:
        description: 'The architecture for the image'
        required: true
    repo-dir: 
        description: 'The directory of the repo'
        required: true
    app-name:
        description: 'The name of the app'
        required: true
    image-tag:
        description: 'The image tag'
        type: string
        required: false
    annotation-config:
        description: 'The annotation config'
        required: false
runs:
    using: 'composite'
    steps:
        - name: Perform login steps
          shell: bash
          run: |
            source ${{ inputs.env-file }}

            if [ -z "${{ inputs.image-tag }}" ]; then
              image_tag=$SPACEFX_VERSION
            else
              image_tag=${{ inputs.image-tag }}
            fi

            echo "Running build_containerImage.sh script:"
            echo ""
            bash /var/spacedev/build/build_containerImage.sh --dockerfile ${{ inputs.docker-file }} --image-tag $image_tag --architecture ${{ inputs.architecture }} --repo-dir ${{ inputs.repo-dir }} --app-name ${{ inputs.app-name }} --annotation-config ${{ inputs.annotation-config }}