name: 'install-yq'
description:  'Installs yq'
inputs:
    VER_HELM:
        description: 'The version of yq to install'
        default: '4.44.2'
runs:
    using: 'composite'
    steps:
        - name: Install yq
          shell: bash
          run: |

            arch="$(uname -m)"
            case "$arch" in
              x86_64)
                architecture=amd64
                ;;
              aarch64)
                architecture=arm64
                ;;
              *)
                echo "Unsupported architecture: $arch"
                exit 1
                ;;
            esac

            echo "Installing yq version ${{ inputs.VER_HELM }} for ${architecture:?}"
            echo "...downloading yq (https://github.com/mikefarah/yq/releases/download/v${{ inputs.VER_HELM }}/yq_linux_$architecture)..."
            curl --silent --fail --create-dirs --output "/usr/local/bin/yq" -L "https://github.com/mikefarah/yq/releases/download/v${{ inputs.VER_HELM }}/yq_linux_$architecture"
            echo "...yq downloaded..."


            echo "Adding execute permissions to yq"
            chmod +x /usr/local/bin/yq
            chmod 755 /usr/local/bin/yq

            echo "Checking yq version"
            yq --version