name: 'sign-container-image'
description:  'Performs a signing of the container image.'
inputs:
    COSIGN_PRIVATE_KEY:
        description: 'The private key to use for signing the container image.'
        required: true
    CONTAINER_REPOSITORY:
        description: 'The container repository to sign.'
        required: true
runs:
    using: 'composite'
    steps:
      - name: Install Cosign
        shell: bash
        run: |
          VERSION=$(curl --location "https://api.github.com/repos/sigstore/cosign/releases/latest" | jq --raw-output .tag_name)
          curl --location "https://github.com/sigstore/cosign/releases/download/${VERSION}/cosign-linux-amd64" --output cosign
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

      - name: Sign Docker Image
        shell: bash
        run: |
          echo "${{ inputs.COSIGN_PRIVATE_KEY }}" | cosign sign --key /dev/stdin ${{ inputs.CONTAINER_REPOSITORY }}

      - name: Verify Docker Image
        shell: bash
        run: |
          cosign verify --key cosign.pub ${{ inputs.CONTAINER_REPOSITORY }}