name: Run Action tests

on:
  workflow_dispatch:
  push:
        branches:
        - km/add_attestation
  pull_request:
    branches:
      - '**'

jobs:
  test-get-agent-details-amd64:
    permissions:
      contents: read
      packages: read
    
    uses: ./.github/workflows/test-get-agent-details.yaml
    with: 
      agent: ubuntu-latest

  test-get-agent-details-arm64:
    permissions:
      contents: read
      packages: read
    
    uses: ./.github/workflows/test-get-agent-details.yaml
    with: 
      agent: spacesdk-ubuntu-2204LTS-arm64

  test-install-regctl-amd64:
    permissions:
      contents: read
      packages: read
    
    uses: ./.github/workflows/test-install-regctl.yaml
    with: 
      env_file: ./test-artifacts/test-install-regctl/test.env
      agent: ubuntu-latest

  test-install-regctl-arm64:
    permissions:
      contents: read
      packages: read
    
    uses: ./.github/workflows/test-install-regctl.yaml
    with: 
      env_file: ./test-artifacts/test-install-regctl/test.env
      agent: spacesdk-ubuntu-2204LTS-arm64

  test-install-docker-amd64:
    permissions:
      contents: read
      packages: read
    
    uses: ./.github/workflows/test-install-docker.yaml
    with: 
      VER_DOCKER_MAX: 26.1.3
      agent: ubuntu-latest

  test-install-docker-arm64:
    permissions:
      contents: read
      packages: read
    
    uses: ./.github/workflows/test-install-docker.yaml
    with: 
      VER_DOCKER_MAX: 26.1.3
      agent: spacesdk-ubuntu-2204LTS-arm64

  test-container-attestation-amd64:
    permissions:
      contents: read
      packages: write
    
    uses: ./.github/workflows/test-attest-container.yaml
    with: 
      VER_DOCKER_MAX: 26.1.3
      agent: ubuntu-latest
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}

  test-container-attestation-arm64:
    permissions:
      contents: read
      packages: write
    
    uses: ./.github/workflows/test-attest-container.yaml
    with: 
      VER_DOCKER_MAX: 26.1.3
      agent: spacesdk-ubuntu-2204LTS-arm64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
