name: Shared- service-build workflow
on: 
    workflow_call:
        inputs:
            APP_PROJECT:
              description: 'The project to build'
              required: true
              type: string
            NUGET_PROJECT:
              description: 'The nuget project to build'
              type: string
            OUTPUT_DIR:
              description: 'The output directory for the build'
              required: true
              type: string
            NUGET_STAGING_DIRECTORY:
              description: 'The staging directory for the nuget packages'
              required: true
              type: string
            NUGET_FILE_PREFIX:
              description: 'The prefix for the nuget file'
              required: true
              type: string
            ANNOTATION:
              description: 'Annotation file'
              required: true
              type: string
            WORKFLOW_AGENT:
              description: 'The name of the workflow agent'
              type: string
              default: 'ubuntu-latest'
            ARCHITECTURE:
              description: 'The architecture for the image'
              required: true
              type: string
            SPACESDK_VERSION:
              description: 'The version of the space sdk'
              type: string
              default: "0.11.0"
            CONTAINER_IMAGE_NAME:
              description: 'The name of the container image'
              required: true
              type: string
        secrets:
            GIT_HUB_USER_NAME:
                required: true
            GIT_HUB_USER_TOKEN:
                required: true
            SETUP_REPO_URL:
                required: true

jobs:
  build-core-service:
    runs-on: ${{ inputs.WORKFLOW_AGENT }}

    permissions:
      contents: read
      packages: write

    steps:
    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@main
      with:
        GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
        GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
        SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/build-app@main
      with:
        ARCHITECTURE: ${{ inputs.ARCHITECTURE }}
        APP_PROJECT: ${{ inputs.APP_PROJECT}}
        NUGET_PROJECT: ${{ inputs.NUGET_PROJECT}}
        APP_VERSION: ${{ inputs.SPACESDK_VERSION }}
        OUTPUT_DIR: ${{ inputs.OUTPUT_DIR }}
        ANNOTATION_CONFIG: ${{ inputs.ANNOTATION}}
        NO_CONTAINER_BUILD: 'false'

    - id: docker_meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: ${{ inputs.CONTAINER_IMAGE_NAME }}:${{ inputs.SPACESDK_VERSION }}
        tags: type=sha,format=long

    - name: cosign-installer
      uses: sigstore/cosign-installer@v3.5.0

    - name: cosign-install
      run: cosign version

    - name: Sign image with a key
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
      env:
        TAGS: ${{ steps.docker_meta.outputs.tags }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        
    - name: Move file to staging directory
      shell: bash
      run: |
        sudo mkdir -p ${{ inputs.NUGET_STAGING_DIRECTORY }}

        sudo cp ${{ inputs.OUTPUT_DIR }}/${{ inputs.ARCHITECTURE }}/nuget/${{ inputs.NUGET_FILE_PREFIX }}.${{ inputs.SPACESDK_VERSION }}.nupkg ${{ inputs.NUGET_STAGING_DIRECTORY }}
        tree ${{ inputs.NUGET_STAGING_DIRECTORY }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/push-build-artifact@main
      with:
        artifact: ${{ inputs.NUGET_STAGING_DIRECTORY }}/${{ inputs.NUGET_FILE_PREFIX }}.${{ inputs.SPACESDK_VERSION }}.nupkg
        architecture: ${{ inputs.ARCHITECTURE }}