name: Test container signing
on: 
    workflow_call:
      inputs:
        agent:
          description: 'The agent to run the job on'
          required: true
          type: string
        architecture:
          description: 'The architecture of the agent'
          required: true
          type: string
      secrets:
        GIT_HUB_USER_NAME:
            required: true
        GIT_HUB_USER_TOKEN:
            required: true
        SETUP_REPO_URL:
            required: true

jobs:
  test-container-signing:
    runs-on: ${{ inputs.agent }}

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/initialize@main
      with:
        GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
        GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
        SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-cosign@km/adding_container_signing
      with:
        architecture: ${{ inputs.ARCHITECTURE }}

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/image-sign-container@km/adding_container_signing
      with:
        container-repository-name: 'testing-signing'
        container-repository-tag: 'latest'
        cosign-public-key: ${{ secrets.COSIGN_PUBLIC_KEY }}
        cosign-private-key: ${{ secrets.COSIGN_PRIVATE_KEY }}
        cosign-passphrase:  ${{ secrets.COSIGN_PASSPHRASE }}
        