on:
  workflow_call:
    inputs:
      agent:
        description: 'The agent to run the job on'
        required: true
        type: string

jobs:
  test-install-devcontainer-cli:
    runs-on: ${{ inputs.agent }}

    steps:
    - uses: actions/checkout@v2

    - uses: microsoft/azure-orbital-space-sdk-github-actions/composite-actions/install-devcontainer-cli@main

    - name: Validate Devcontainer stool installed correctly
      shell: bash
      run: |
        devcontainer --help
